@echo off
echo Installing dependencies...
call npm install

echo Installing firebase-admin (if needed)...
call npm install firebase-admin --no-save

echo Building Next.js application...
call npm run build

echo Checking if out directory exists...
if not exist out (
  echo Creating out directory manually...
  mkdir out
  echo Creating placeholder index.html...
  echo ^<!DOCTYPE html^>^<html^>^<head^>^<title^>Denarii^</title^>^</head^>^<body^>^<div id="root"^>^</div^>^</body^>^</html^> > out\index.html
)

echo Deploying to Firebase hosting...
call firebase deploy --only hosting

echo Deployment complete!